---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/master/docker/data/logstash/config/logstash-full.yml
#
#http.host: "0.0.0.0"
#xpack.monitoring.elasticsearch.hosts: [ "http://localhost:9200" ]

## X-Pack security credentials
#xpack.management.logstash.poll_interval: 5s
#xpack.management.pipeline.id: ["apache", "cloudwatch_logs"]#
#xpack.monitoring.enabled: true
#xpack.monitoring.elasticsearch.username: elastic
#xpack.monitoring.elasticsearch.password: changeme

http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
